#!/usr/bin/env python
# coding: utf-8

# In[3]:


def bubbleSort(arr):
    n = len(arr)
    for i in range(n):
   
       for j in range(0, n-i-1):
          if arr[j] > arr[j+1] :
              arr[j], arr[j+1] = arr[j+1], arr[j]
    for i in range(len(arr)):
        print (arr[i]) 


# In[2]:


bubbleSort(['s','a','n','i','y','a'])


# In[ ]:




