/**
 * Componente Curricular: Módulo Integrado de Programação II
 * Autor: <Roberto Maia Rodrigues Junior e Daniel Cavalcante Dourado>
 * Data:  <07/02/2019>
 *
 * Declaro que este código foi elaborado por mim de forma individual e não
 * contém nenhum trecho de código de outro colega ou de outro autor, tais como
 * provindos de livros e apostilas, e páginas ou documentos eletrônicos da
 * Internet. Qualquer trecho de código de outra autoria que uma citação para o
 * não a minha está destacado com autor e a fonte do código, e estou ciente que
 * estes trechos não serão considerados para fins de avaliação. Alguns trechos
 * do código podem coincidir com de outros colegas pois estes foram discutidos
 * em sessões tutorias.
 */
package view;

import controller.Controller;
import exception.FinalizarRotaException;
import exception.MinhaException;
import exception.NenhumaCidadeSelecionadaException;
import exception.RotaNaoCalculadaException;
import static java.awt.Color.blue;
import static java.awt.Color.red;
import java.awt.Graphics;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cidade;
import model.Grafo;

/**
 * Classe JFrame principal do sistema.
 *
 * @author Roberto Maia
 * @author Daniel Dourado
 */
public class SistemaDeRoteamento extends javax.swing.JFrame {

    /**
     * Creates new form SistemaDeRoteamento2
     */
    public SistemaDeRoteamento() {
        initComponents();
        PanelGrafo grafo = new PanelGrafo();
        this.jPanelMapa.add(grafo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMapa = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanelRota = new javax.swing.JPanel();
        jLabelOrigem = new javax.swing.JLabel();
        jLabelParadas = new javax.swing.JLabel();
        jComboBoxParadas = new javax.swing.JComboBox<>();
        jLabelDestino = new javax.swing.JLabel();
        jLabelMenorDistancia = new javax.swing.JLabel();
        jPanelTutorial = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCancelarRota = new javax.swing.JButton();
        btnFinalizarRota = new javax.swing.JButton();
        jPanelVeiculo = new javax.swing.JPanel();
        jLabelValorCombustivel = new javax.swing.JLabel();
        jLabelConsumoVeiculo = new javax.swing.JLabel();
        jLabelValorCombustivelInfo = new javax.swing.JLabel();
        jLabelConsumoInfo = new javax.swing.JLabel();
        jLabelGasto = new javax.swing.JLabel();
        jLabelGastoInfo = new javax.swing.JLabel();
        btnCalcularRota = new javax.swing.JButton();
        jButtonAjuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Roteamento");
        setBackground(new java.awt.Color(72, 120, 170));
        setPreferredSize(new java.awt.Dimension(1440, 900));

        jPanelMapa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "MAPA:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanelMapa.setPreferredSize(new java.awt.Dimension(1500, 870));
        jPanelMapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelMapaMouseClicked(evt);
            }
        });
        jPanelMapa.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(72, 120, 170));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanelRota.setBackground(new java.awt.Color(72, 120, 170));
        jPanelRota.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)), "ROTA:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(240, 240, 240))); // NOI18N

        jLabelOrigem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOrigem.setForeground(new java.awt.Color(240, 240, 240));
        jLabelOrigem.setText("Origem: Feira de Santana");

        jLabelParadas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelParadas.setForeground(new java.awt.Color(240, 240, 240));
        jLabelParadas.setText("Roteiro:");

        jComboBoxParadas.setPreferredSize(new java.awt.Dimension(31, 25));

        jLabelDestino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDestino.setForeground(new java.awt.Color(240, 240, 240));
        jLabelDestino.setText("Destino:");

        jLabelMenorDistancia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMenorDistancia.setForeground(new java.awt.Color(240, 240, 240));
        jLabelMenorDistancia.setText("Menor distância:");

        javax.swing.GroupLayout jPanelRotaLayout = new javax.swing.GroupLayout(jPanelRota);
        jPanelRota.setLayout(jPanelRotaLayout);
        jPanelRotaLayout.setHorizontalGroup(
            jPanelRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBoxParadas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelRotaLayout.createSequentialGroup()
                .addGroup(jPanelRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOrigem)
                    .addComponent(jLabelDestino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelRotaLayout.createSequentialGroup()
                .addGroup(jPanelRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelParadas)
                    .addComponent(jLabelMenorDistancia))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelRotaLayout.setVerticalGroup(
            jPanelRotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRotaLayout.createSequentialGroup()
                .addComponent(jLabelOrigem)
                .addGap(18, 18, 18)
                .addComponent(jLabelDestino)
                .addGap(18, 18, 18)
                .addComponent(jLabelParadas)
                .addGap(12, 12, 12)
                .addComponent(jComboBoxParadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMenorDistancia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelTutorial.setBackground(new java.awt.Color(72, 120, 170));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Sistema de Roteamento V 1.0");

        btnCancelarRota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelarRota.setText("Cancelar rota");
        btnCancelarRota.setPreferredSize(new java.awt.Dimension(220, 35));
        btnCancelarRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarRotaActionPerformed(evt);
            }
        });

        btnFinalizarRota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFinalizarRota.setText("Finalizar rota");
        btnFinalizarRota.setPreferredSize(new java.awt.Dimension(121, 35));
        btnFinalizarRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarRotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTutorialLayout = new javax.swing.GroupLayout(jPanelTutorial);
        jPanelTutorial.setLayout(jPanelTutorialLayout);
        jPanelTutorialLayout.setHorizontalGroup(
            jPanelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTutorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTutorialLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFinalizarRota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelarRota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanelTutorialLayout.setVerticalGroup(
            jPanelTutorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTutorialLayout.createSequentialGroup()
                .addComponent(btnCancelarRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizarRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanelVeiculo.setBackground(new java.awt.Color(72, 120, 170));
        jPanelVeiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true), "VEICULO:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(240, 240, 240))); // NOI18N
        jPanelVeiculo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabelValorCombustivel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValorCombustivel.setForeground(new java.awt.Color(240, 240, 240));
        jLabelValorCombustivel.setText("Valor do combustivel:");

        jLabelConsumoVeiculo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelConsumoVeiculo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelConsumoVeiculo.setText("Consumo do veiculo:");

        jLabelValorCombustivelInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValorCombustivelInfo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelValorCombustivelInfo.setText("R$3,45");

        jLabelConsumoInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelConsumoInfo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelConsumoInfo.setText("7.5Km/L");

        jLabelGasto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelGasto.setForeground(new java.awt.Color(240, 240, 240));
        jLabelGasto.setText("Gasto da viagem:");

        jLabelGastoInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelGastoInfo.setForeground(new java.awt.Color(240, 240, 240));
        jLabelGastoInfo.setText("-----");

        javax.swing.GroupLayout jPanelVeiculoLayout = new javax.swing.GroupLayout(jPanelVeiculo);
        jPanelVeiculo.setLayout(jPanelVeiculoLayout);
        jPanelVeiculoLayout.setHorizontalGroup(
            jPanelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVeiculoLayout.createSequentialGroup()
                .addGroup(jPanelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelValorCombustivel)
                    .addComponent(jLabelConsumoVeiculo)
                    .addComponent(jLabelValorCombustivelInfo)
                    .addComponent(jLabelConsumoInfo)
                    .addComponent(jLabelGasto)
                    .addComponent(jLabelGastoInfo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVeiculoLayout.setVerticalGroup(
            jPanelVeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVeiculoLayout.createSequentialGroup()
                .addComponent(jLabelValorCombustivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValorCombustivelInfo)
                .addGap(18, 18, 18)
                .addComponent(jLabelConsumoVeiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelConsumoInfo)
                .addGap(18, 18, 18)
                .addComponent(jLabelGasto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGastoInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCalcularRota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCalcularRota.setText("Calcular rota");
        btnCalcularRota.setPreferredSize(new java.awt.Dimension(220, 35));
        btnCalcularRota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularRotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTutorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCalcularRota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelRota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelRota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcularRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTutorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAjuda.setBackground(new java.awt.Color(255, 213, 0));
        jButtonAjuda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAjuda.setText("Ajuda");
        jButtonAjuda.setToolTipText("");
        jButtonAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMapa, javax.swing.GroupLayout.DEFAULT_SIZE, 1187, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelMapa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAjuda)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Cidade cidades[];
    Controller principal = new Controller();
    Cidade[] cidadesSelecionadas = new Cidade[31];
    int qtdCidadesSelecionadas = 0, controleRota = 0;
    Grafo resultado = new Grafo();
    double distanciaTotal, distanciaIda, distanciaVolta;
    String caminhoIda, caminhoVolta;

    /**
     * Evento relacionado ao botão de ajuda, esse evento é responsável por
     * auxiliar o usuário quanto ao uso do software.
     *
     * @param evt
     */
    private void jButtonAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaActionPerformed
        JOptionPane.showMessageDialog(jPanelMapa, "Como utilizar:\n1º Clique nas cidades que deseja passar. A última cidade selecionada será o destino final e as demais serão paradas.\n2º Verifique as paradas selecionadas..\n3º Clique em calcular rota \n4º Caso satisfeito, finalize a rota, caso contrário, cancele a rota e faça novamente.\n\n Obs: Não é possível selecionar Feira de Santana, pois é a cidade origem para todas as viagens.");
    }//GEN-LAST:event_jButtonAjudaActionPerformed

    /**
     * Método responsável por selecionar as cidades do roteiro a partir do
     * clique no panel do mapa.
     *
     * @param evt
     */
    private void jPanelMapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelMapaMouseClicked
        int x, y;
        Graphics g = jPanelMapa.getGraphics();
        x = evt.getX();
        y = evt.getY();
        int cidadeRepetida = 0;
        try {
            cidades = principal.lerArquivoCidades();
            int controle = qtdCidadesSelecionadas;
            for (int i = 1; i < 32; i++) {
                if (qtdCidadesSelecionadas > controle) {
                    break;
                }
                int cidadeX = (int) ((cidades[i].getCoordenadaX() - 340) * 1.5);
                int cidadeY = (int) ((cidades[i].getCoordenadaY() - 50) * 1.25);
                for (int j = 0; j < 40; j++) {
                    if (x - j == cidadeX) {
                        for (int h = 0; h < 40; h++) {
                            if (y - h == cidadeY) {
                                for (int b = 0; b < qtdCidadesSelecionadas; b++) {
                                    if (cidadesSelecionadas[b].getNomeCidade().equalsIgnoreCase(cidades[i].getNomeCidade())) {
                                        cidadeRepetida = 1;
                                    }
                                }
                                if (cidadeRepetida == 0) {
                                    cidadesSelecionadas[qtdCidadesSelecionadas] = cidades[i];
                                    jComboBoxParadas.addItem(cidades[i].getNomeCidade());
                                    qtdCidadesSelecionadas++;
                                    g.setColor(red);
                                    g.fillOval(cidadeX + 5, cidadeY + 27, 21, 21);
                                    break;
                                }
                            }

                        }
                        if (qtdCidadesSelecionadas > controle) {
                            break;
                        }
                    }

                }
            }

        } catch (IOException ex) {
            Logger.getLogger(SistemaDeRoteamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanelMapaMouseClicked

    /**
     * Evento relacionado ao botão calcular rota, cuja função é definir a rota,
     * a distância de ida, volta e total.
     *
     * @param evt
     */
    private void btnCalcularRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularRotaActionPerformed

        try {
            FileWriter fileWrite = new FileWriter("./Rotas Saida.txt", true);
            BufferedWriter bufferedWriter = new BufferedWriter(fileWrite);
            Controller c1 = new Controller();
            c1.AddArestas();
            if (controleRota == 0) {
                if (qtdCidadesSelecionadas > 0) {
                    //bufferedWriter.write("TRAJETORIA DE IDA :");
                    bufferedWriter.newLine();
                    //bufferedWriter.write("Origem: Feira de Santana");
                    jLabelDestino.setText("Destino: " + cidadesSelecionadas[qtdCidadesSelecionadas - 1].getNomeCidade());
                    Grafo aux = new Grafo();
                    aux.setVertices(c1.menorCaminho("Feira de Santana", cidadesSelecionadas[0].getNomeCidade()));
                    distanciaIda += aux.imprimeArvore();
                    for (int r = 0; r < qtdCidadesSelecionadas - 1; r++) {
                        Controller c2 = new Controller();
                        c2.AddArestas();
                        Grafo aux1 = new Grafo();
                        aux1.setVertices(c2.menorCaminho(cidadesSelecionadas[r].getNomeCidade(), cidadesSelecionadas[r + 1].getNomeCidade()));
                        distanciaIda += aux1.imprimeArvore();
                    }

                    bufferedWriter.write("Distância Total da Ida: " + distanciaIda + "KM" + "\n");
                    bufferedWriter.newLine();

                    Controller c3 = new Controller();
                    c3.AddArestas();
                    aux.setVertices(c3.menorCaminho(cidadesSelecionadas[qtdCidadesSelecionadas - 1].getNomeCidade(), "Feira de Santana"));
                    distanciaVolta = aux.imprimeArvoreVolta();
                    bufferedWriter.write("Distância Total da Volta: " + distanciaVolta + "KM" + "\n");
                    distanciaTotal += distanciaVolta + distanciaIda;
                    bufferedWriter.newLine();
                    bufferedWriter.write("Distância Total: " + distanciaTotal + "KM");
                    controleRota = 1;
                    bufferedWriter.newLine();
                    bufferedWriter.write("Custo total viagem: R$" + Double.toString(principal.calcularValor(distanciaTotal)));
                    bufferedWriter.newLine();
                    bufferedWriter.write("------------------------");
                    bufferedWriter.newLine();
                    jLabelMenorDistancia.setText(jLabelMenorDistancia.getText() + " " + Double.toString(distanciaTotal) + " KM");
                    jLabelGastoInfo.setText("R$" + Double.toString(principal.calcularValor(distanciaTotal)));
                    bufferedWriter.newLine();
                    bufferedWriter.close();
                } else {
                    throw new NenhumaCidadeSelecionadaException();
                }
            } else {
                throw new FinalizarRotaException();
            }
        } catch (MinhaException e) {
            JOptionPane.showMessageDialog(jPanelMapa, e.getMsg());

        } catch (IOException ex) {
            Logger.getLogger(SistemaDeRoteamento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCalcularRotaActionPerformed

    /**
     * Evento relacionado ao botão de finalizar rota, cuja função é finalizar a
     * rota calculada e limpar as modificações na interface.
     *
     * @param evt
     */
    private void btnFinalizarRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarRotaActionPerformed
        Graphics g = jPanelMapa.getGraphics();
        try {
            if (controleRota == 1) {
                if (qtdCidadesSelecionadas > 0) {
                    for (int i = 0; i < qtdCidadesSelecionadas; i++) {
                        int cidadeX = (int) ((cidadesSelecionadas[i].getCoordenadaX() - 340) * 1.5);
                        int cidadeY = (int) ((cidadesSelecionadas[i].getCoordenadaY() - 50) * 1.25);
                        g.setColor(blue);
                        g.fillOval(cidadeX + 5, cidadeY + 27, 21, 21);
                        cidadesSelecionadas[i] = null;
                    }
                    qtdCidadesSelecionadas = 0;
                    controleRota = 0;
                    jComboBoxParadas.removeAllItems();
                    jLabelDestino.setText("Destino:");
                    jLabelMenorDistancia.setText("Menor caminho:");
                    jLabelGastoInfo.setText("-----");
                    distanciaTotal = 0;
                    distanciaIda = 0;
                    distanciaVolta = 0;
                } else {
                    throw new NenhumaCidadeSelecionadaException();
                }

            } else {
                throw new RotaNaoCalculadaException();
            }
        } catch (MinhaException e) {
            JOptionPane.showMessageDialog(jPanelMapa, e.getMsg());
        }

    }//GEN-LAST:event_btnFinalizarRotaActionPerformed

    /**
     * Evento relacionado ao botão de cancelar rota, cuja função é cancelar a
     * calculada.
     *
     * @param evt
     */
    private void btnCancelarRotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarRotaActionPerformed

        Graphics g = jPanelMapa.getGraphics();
        try {
            if (qtdCidadesSelecionadas > 0) {
                for (int i = 0; i < qtdCidadesSelecionadas; i++) {
                    int cidadeX = (int) ((cidadesSelecionadas[i].getCoordenadaX() - 340) * 1.5);
                    int cidadeY = (int) ((cidadesSelecionadas[i].getCoordenadaY() - 50) * 1.25);
                    g.setColor(blue);
                    g.fillOval(cidadeX + 5, cidadeY + 27, 21, 21);
                    cidadesSelecionadas[i] = null;
                }
                qtdCidadesSelecionadas = 0;
                controleRota = 0;
                jComboBoxParadas.removeAllItems();
                System.out.println("Rota cancelada com sucesso.");
                jLabelDestino.setText("Destino:");
                jLabelMenorDistancia.setText("Menor caminho:");
                jLabelGastoInfo.setText("-----");
            } else {
                throw new NenhumaCidadeSelecionadaException();
            }
        } catch (MinhaException e) {
            JOptionPane.showMessageDialog(jPanelMapa, e.getMsg());

        }
    }//GEN-LAST:event_btnCancelarRotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaDeRoteamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaDeRoteamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaDeRoteamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaDeRoteamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SistemaDeRoteamento().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularRota;
    private javax.swing.JButton btnCancelarRota;
    private javax.swing.JButton btnFinalizarRota;
    private javax.swing.JButton jButtonAjuda;
    private javax.swing.JComboBox<String> jComboBoxParadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelConsumoInfo;
    private javax.swing.JLabel jLabelConsumoVeiculo;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelGasto;
    private javax.swing.JLabel jLabelGastoInfo;
    private javax.swing.JLabel jLabelMenorDistancia;
    private javax.swing.JLabel jLabelOrigem;
    private javax.swing.JLabel jLabelParadas;
    private javax.swing.JLabel jLabelValorCombustivel;
    private javax.swing.JLabel jLabelValorCombustivelInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelMapa;
    private javax.swing.JPanel jPanelRota;
    private javax.swing.JPanel jPanelTutorial;
    private javax.swing.JPanel jPanelVeiculo;
    // End of variables declaration//GEN-END:variables
}
