import turtle
import random

a = random.randint(1,6)
print(a)

def DICE():
    if a == 1:
        t = turtle.Turtle()
        t.color('red')
        t.width(2)
        t.speed(3)

        for i in range(4):
            t.forward(75)
            t.left(90)

        t.left(45)
        t.penup()
        t.forward(50)
        t.pendown()
        t.circle(3)
        t.penup()
        t.forward(100)
        t.pendown()

    elif a == 2:
        d = turtle.Pen()
        turtle.colormode(255)
        d.color(0,0,255)
        d.width(2)
        d.speed(3)

        for i in range(4):
           d.forward(75)
           d.left(90)

        d.left(30)
        d.penup()        
        d.forward(45)
        d.pendown()
        d.circle(3)
        d.left(55)
        d.penup()
        d.forward(27)
        d.pendown()
        d.circle(3)
        d.penup()
        d.forward(50)
        d.pendown()
    elif a == 3:
        y = turtle.Turtle()
        turtle.colormode(255)
        y.color(255,0,0)
        y.width(2)
        y.speed(3)

        for i in range(4):
            y.forward(75)
            y.left(90)

        y.left(45)
        y.penup()
        y.forward(25)
        y.pendown()
        y.circle(3)
        y.right(45)
        y.penup()
        y.forward(45)
        y.pendown()
        y.circle(3)
        y.left(123)
        y.penup()
        y.forward(40)
        y.pendown()
        y.circle(3)
        y.penup()
        y.forward(50)
        y.pendown()
        
    elif a == 4:
        f = turtle.Turtle()
        turtle.colormode(255)
        f.color(0,0,255)
        f.width(2)
        f.speed(3)
        
        for i in range(4):
            f.forward(75)
            f.left(90)

        f.left(45)
        f.penup()
        f.forward(20)
        f.pendown()
        f.right(45)
        f.circle(3)
        f.penup()
        f.forward(50)
        f.pendown()
        f.circle(3)
        f.left(90)
        f.penup()
        f.forward(50)
        f.pendown()
        f.circle(3)
        f.left(90)
        f.penup()
        f.forward(50)
        f.pendown()
        f.circle(3)
        f.penup()
        f.forward(50)
        f.pendown()
        
    elif a == 5:
        i = turtle.Pen()
        turtle.colormode(255)
        i.color(255,0,0)
        i.width(2)
        i.speed(3)

        for x in range (4):
            i.forward(75)
            i.left(90)

        i.left(45)
        i.penup()
        i.forward(20)
        i.pendown()
        i.right(45)
        i.circle(3)
        i.penup()
        i.forward(50)
        i.pendown()
        i.circle(3)
        i.left(90)
        i.penup()
        i.forward(50)
        i.pendown()
        i.circle(3)
        i.left(90)
        i.penup()
        i.forward(50)
        i.pendown()
        i.circle(3)
        i.left(127)
        i.penup()
        i.forward(35)
        i.pendown()
        i.circle(3)
        i.penup()
        i.forward(150)
        i.pendown()
        
    elif a == 6:
        s = turtle.Pen()
        turtle.colormode(255)
        s.color(0,0,0)
        s.width(2)
        s.speed(3)

        for i in range(4):
            s.forward(75)
            s.left(90)

        s.left(45)
        s.penup()
        s.forward(20)
        s.pendown()
        s.right(45)
        s.circle(3)
        s.penup()
        s.forward(50)
        s.pendown()
        s.circle(3)
        s.left(90)
        s.penup()
        s.forward(25)
        s.pendown()
        s.circle(3)
        s.penup()
        s.forward(25)
        s.pendown()
        s.circle(3)
        s.left(90)
        s.penup()
        s.forward(50)
        s.pendown()
        s.circle(3)
        s.left(90)
        s.penup()
        s.forward(25)
        s.pendown()
        s.circle(3)
        s.penup()
        s.forward(100)
        s.pendown()
        
DICE()
